# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e066af34b89a7630d4716d0ab46c9870463456bfa3ba3a62e460ca32a74960a18c864276dbddbca474f7dc8a7fea93f281333fa53df2693a2c9caa56c986e3c5

test:
  secret_key_base: e599cd62f0f7cd155b8aecf95b2e5cc0df3139680eb46a2372e6653bd0ef2ab8bab9b7f943dfe63e2f42ab5dad3c525d2122621774ca29c9ca6e76c533594c77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
